---
include:
  - board: planck_left
  - board: planck_right
  - board: nice_nano_v2
      shield: eyeslash_central_dongle dongle_display
      snippet: studio-rpc-usb-uart
      cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
